apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-service
spec:
  type: NodePort
  ports:
    - port: 80  # The port that your application is listening on
      targetPort: 80  # Port on the container
      nodePort: 30002  # This can be any port in the range 30000-32767
  selector:
    app: netflix-clone
